CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS phishing_links (
    id INTEGER PRIMARY KEY,
    url TEXT NOT NULL,
    redirect_url TEXT,
    ip TEXT,
    countrycode TEXT,
    countryname TEXT,
    regioncode TEXT,
    regionname TEXT,
    city TEXT,
    zipcode TEXT,
    latitude REAL,
    longitude REAL,
    asn TEXT,
    bgp TEXT,
    isp TEXT,
    title TEXT,
    date TEXT,
    date_update TEXT,
    hash TEXT,
    score REAL,
    host TEXT,
    domain TEXT,
    tld TEXT,
    domain_registered_n_days_ago INTEGER,
    screenshot TEXT,
    abuse_contact TEXT,
    ssl_issuer TEXT,
    ssl_subject TEXT,
    rank_host INTEGER,
    rank_domain INTEGER,
    n_times_seen_ip INTEGER,
    n_times_seen_host INTEGER,
    n_times_seen_domain INTEGER,
    http_code INTEGER,
    http_server TEXT,
    google_safebrowsing TEXT,
    virus_total TEXT,
    abuse_ch_malware TEXT,
    vulns TEXT,
    ports TEXT,
    os TEXT,
    tags TEXT,
    technology TEXT,
    page_text TEXT,
    ssl_fingerprint TEXT,
    inserted_at TEXT DEFAULT CURRENT_TIMESTAMP
);
"""

UPSERT_SQL = """
INSERT INTO phishing_links (
    id,
    url,
    redirect_url,
    ip,
    countrycode,
    countryname,
    regioncode,
    regionname,
    city,
    zipcode,
    latitude,
    longitude,
    asn,
    bgp,
    isp,
    title,
    date,
    date_update,
    hash,
    score,
    host,
    domain,
    tld,
    domain_registered_n_days_ago,
    screenshot,
    abuse_contact,
    ssl_issuer,
    ssl_subject,
    rank_host,
    rank_domain,
    n_times_seen_ip,
    n_times_seen_host,
    n_times_seen_domain,
    http_code,
    http_server,
    google_safebrowsing,
    virus_total,
    abuse_ch_malware,
    vulns,
    ports,
    os,
    tags,
    technology,
    page_text,
    ssl_fingerprint
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    url = excluded.url,
    redirect_url = excluded.redirect_url,
    ip = excluded.ip,
    countrycode = excluded.countrycode,
    countryname = excluded.countryname,
    regioncode = excluded.regioncode,
    regionname = excluded.regionname,
    city = excluded.city,
    zipcode = excluded.zipcode,
    latitude = excluded.latitude,
    longitude = excluded.longitude,
    asn = excluded.asn,
    bgp = excluded.bgp,
    isp = excluded.isp,
    title = excluded.title,
    date = excluded.date,
    date_update = excluded.date_update,
    hash = excluded.hash,
    score = excluded.score,
    host = excluded.host,
    domain = excluded.domain,
    tld = excluded.tld,
    domain_registered_n_days_ago = excluded.domain_registered_n_days_ago,
    screenshot = excluded.screenshot,
    abuse_contact = excluded.abuse_contact,
    ssl_issuer = excluded.ssl_issuer,
    ssl_subject = excluded.ssl_subject,
    rank_host = excluded.rank_host,
    rank_domain = excluded.rank_domain,
    n_times_seen_ip = excluded.n_times_seen_ip,
    n_times_seen_host = excluded.n_times_seen_host,
    n_times_seen_domain = excluded.n_times_seen_domain,
    http_code = excluded.http_code,
    http_server = excluded.http_server,
    google_safebrowsing = excluded.google_safebrowsing,
    virus_total = excluded.virus_total,
    abuse_ch_malware = excluded.abuse_ch_malware,
    vulns = excluded.vulns,
    ports = excluded.ports,
    os = excluded.os,
    tags = excluded.tags,
    technology = excluded.technology,
    page_text = excluded.page_text,
    ssl_fingerprint = excluded.ssl_fingerprint
"""

GET_OLDEST_DATE_SQL = "SELECT MIN(date) AS oldest_date FROM phishing_links"
